name: Publish Gem

on:
  workflow_dispatch:

jobs:
  bundle-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
      - run: bundle install
      - run: rake test

  publish-gem:
    needs: bundle-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
          AGILIX_BUZZ_USERNAME: "${{ secrets.AGILIX_BUZZ_USERNAME }}"
          AGILIX_BUZZ_PASSWORD: "${{ secrets.AGILIX_BUZZ_PASSWORD }}"
          
  notify_deployment:
    name: Notify Deployment
    needs: publish-gem
    uses: strongmind/public-reusable-workflows/.github/workflows/send-deployment-notification.yml@main
    with:
      repository_name: ${{ github.repository }}
    secrets: inherit
